CREATE DATABASE IF NOT EXISTS GESTION_VETERINARIA;
USE GESTION_VETERINARIA;

CREATE TABLE DUENOS (
    IdDueno  INT AUTO_INCREMENT PRIMARY KEY,
    Nombre   VARCHAR(80) NOT NULL,
    Telefono VARCHAR(20)
);

CREATE TABLE MASCOTAS (
    IdMascota INT AUTO_INCREMENT PRIMARY KEY,
    IdDueno   INT NOT NULL,
    Nombre    VARCHAR(50) NOT NULL,
    Especie   VARCHAR(30) NOT NULL,
    Raza      VARCHAR(50),
    Edad      INT,
    CONSTRAINT FK_MASCOTAS_DUENOS FOREIGN KEY (IdDueno) REFERENCES DUENOS (IdDueno)
);

CREATE TABLE CITAS_VETERINARIAS (
    IdCita   INT AUTO_INCREMENT PRIMARY KEY,
    IdMascota INT NOT NULL,
    Fecha    DATE NOT NULL,
    Motivo   VARCHAR(150),
    Estado   VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT FK_CITASVET_MASCOTAS FOREIGN KEY (IdMascota) REFERENCES MASCOTAS (IdMascota),
    CONSTRAINT CK_CITASVET_ESTADO CHECK (Estado IN ('PENDIENTE', 'ATENDIDA', 'CANCELADA'))
);

CREATE TABLE HISTORIAL_MEDICO (
    IdHistorial INT AUTO_INCREMENT PRIMARY KEY,
    IdMascota   INT NOT NULL,
    Fecha       DATE NOT NULL DEFAULT (CURRENT_DATE),
    Diagnostico VARCHAR(255),
    Tratamiento VARCHAR(255),
    CONSTRAINT FK_HISTORIAL_MASCOTAS FOREIGN KEY (IdMascota) REFERENCES MASCOTAS (IdMascota)
);

INSERT INTO DUENOS (Nombre, Telefono) VALUES
('Adriana Solis', '8877-1122'), ('Manuel Vega', '8877-3344');

INSERT INTO MASCOTAS (IdDueno, Nombre, Especie, Raza, Edad) VALUES
(1, 'Rocky', 'Perro', 'Labrador', 3),
(2, 'Mishi', 'Gato', 'Siames', 2);
